libgeneric-pc: fix possible linker error
undefined reference to symbol 'aio_error@@GLIBC_2.2.5'
.../x86_64-linux-gnu/librt.so: error adding symbols: DSO missing ...


Origin commit data
------------------
Branch: master
Commit: https://github.com/neutrino-images/ni-libstb-hal/commit/f4a9b29ca445fb5d32abd70b66f2ab4e737a7294
Author: Thilo Graf <dbt@novatux.de>
Date: 2019-12-30 (Mon, 30 Dec 2019)



------------------
This commit was generated by Migit